#!/bin/bash
set -x
cd $(dirname $0)

export DNAME=d6.suisuy.eu.org




SLEEP_DURATION=20
while true
do
	for f in *.sh; do bash $f  ; done
        echo all sh finished and will exec again $SLEEP_DURATION seconds
        sleep $SLEEP_DURATION
done
