#!/bin/bash
# chkconfig: 2345 20 80
# description: simple init script 

# Source function library.
#. /etc/init.d/functions

start() {
    # code to start app comes here 
    # example: python3 -m http.server 8080 &
    echo 'myinit executed' >/tmp/myinit.log
     python3 -m http.server 8081 --bind 0.0.0.0 &
}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
    killall myinit
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 